Manage collaborators
CenterForDigitalHumanities/TPEN-interfaces pull request #24
Opened 2024-09-04 16:17 UTC by jsvoo

**Implemented**

- View the list of contributors
- invite a new member
- remove member (from UI)
- error display on UI
- permissions:
   - only the Owner and Leader can view the `remove `button
   - only the Owner and Leader can add new members
 

**Pending Implementation**

- [ ] - remove member from DB
- [ ] - revoke member role
- [ ] move base URL to central point (env?)

**Create New Issue For**
- [ ] populate the `Collaboration` tab with Project title and group title
- [ ] Populate project list with DB data

2024-09-04 19:47 UTC, cubap reviewed
Some comments. I'll let you finish it.

2024-09-04 19:47 UTC, cubap commented on manage/collaboration.html
> +      <button class="default-btn" id="modify-team-btn" projectID="6602dd2314cd575343f513ba" >
Unhardcode the projectID and put it into the querystring, hash, or route

2024-09-04 19:47 UTC, cubap commented on collaborators/index.mjs
> +let testToken = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik9FVTBORFk0T1RVNVJrRXlOREl5TTBFMU1FVXdNMFUyT0RGQk9UaEZSa1JDTXpnek1FSTRNdyJ9.eyJodHRwOi8vc3RvcmUucmVydW0uaW8vYWdlbnQiOiJodHRwczovL3N0b3JlL
okay for a test, but for the PR, this needs to use the auth and login so that it is a portable interface.

2024-09-04 19:47 UTC, cubap commented on collaborators/index.html
> +                      <button id="submit" class="submit-btn">Submit</button>
This is a little odd. Is there a reason it isn't a simple <form> with a normal submit action?
<button> without a `type` is a bit peculiar and I'm not sure that'll work in different browsers as expected.

2024-09-04 19:47 UTC, cubap commented on manage/collaboration.html
These do not really need to look like TPEN28 and it might be harder to reskin it later if it has more than what it needs to be basically functional.

2024-09-04 19:47 UTC, cubap commented on collaborators/index.mjs
> +    const project = await getProjects(projectID)
We get the queryString here, but there is still a hardcoded one.

2024-09-04 19:47 UTC, cubap commented on collaborators/index.mjs
> +async function getProjects(projectID) {
probably singular "Project" is called for here.

2024-09-04 19:47 UTC, cubap commented on collaborators/index.mjs
> +    const project = await getProjects(projectID)
It would be nicer here to use the Project class provided in the Interfaces. It might need some small adjustments, since the service API has changed, but add/remove members, get by id, and other "Project" level stuff will be much easier to manage in that central place. This interface should only have scripts for its own rendering. It might even be preferable to have some simple `Project.html.contributorsAsUnorderedList()` utilities built out later.

2024-09-04 19:47 UTC, cubap commented on collaborators/index.mjs
> +    inviteSectionContainer.style.display = isOwnerOrLeader ? "block" : "none";
This works and I have no problem with it, but in other places we are usually toggling a class that hides.

2024-09-04 19:47 UTC, cubap commented on collaborators/index.mjs
> +    inviteSectionContainer.style.display = isOwnerOrLeader ? "block" : "none";
In fact, an "allow-invite" or similar class would allow you to have one permission check on the page and just add/remove an "is-hidden" class.

2024-09-04 19:47 UTC, cubap commented on collaborators/index.mjs
> +        return roles.join(", ").toLowerCase();
This does the same for the two cases above. `("OWNER").toLowerCase() === "owner"`

2024-09-04 19:47 UTC, cubap commented on collaborators/index.mjs
> +let error = document.getElementById("error")
This is fine for now, but a toast module or something makes sense in the future. Abstracting out errors cleans up a lot of the code.

2024-09-04 19:47 UTC, cubap commented on collaborators/index.mjs
We don't need most of these `;` characters.

2024-09-04 19:47 UTC, cubap commented on collaborators/index.mjs
> +                return error.innerHTML = "Unauthorized request. Please log in to view this resource"
This only grabs 401 errors for the user interface. Would others be helpful to share?

2024-09-04 19:47 UTC, cubap commented on collaborators/index.mjs
> +            console.log(err)
This catch logs the error but it doesn't cause anything else to break and maybe it should.

2024-09-04 19:47 UTC, cubap commented on collaborators/index.mjs
> +        return roles.join(", ").toLowerCase();
I might add a `.replaceAll("_"," ")` as well

2024-09-04 19:47 UTC, cubap commented on css/collaborators/index.css
> +  text-transform: lowercase;
This rule is immediately replaced by the line below and since you are making the Role lowercase, it never does anything, even if `capitalize` isn't supported.

2024-09-04 19:47 UTC, cubap commented on css/collaborators/index.css
> +  text-transform: capitalize;
I like this way of doing it.

2024-09-05 18:01 UTC, jsvoo commented on collaborators/index.html
> +                      <button id="submit" class="submit-btn">Submit</button>
I bound it to a click event. It should work across all browser. for clarity, I have reviewed this and made it a submit button. had to wrap it in a form though

2024-09-05 18:01 UTC, jsvoo commented on manage/collaboration.html
> +      <button class="default-btn" id="modify-team-btn" projectID="6602dd2314cd575343f513ba" >
Done

2024-09-05 18:02 UTC, jsvoo commented on collaborators/index.mjs
> +let testToken = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik9FVTBORFk0T1RVNVJrRXlOREl5TTBFMU1FVXdNMFUyT0RGQk9UaEZSa1JDTXpnek1FSTRNdyJ9.eyJodHRwOi8vc3RvcmUucmVydW0uaW8vYWdlbnQiOiJodHRwczovL3N0b3JlL
I may need to work with you on that @cubap I'm still getting a 400 from auth0 on login/logout from interfaces

2024-09-05 18:03 UTC, jsvoo commented on collaborators/index.mjs
> +    const project = await getProjects(projectID)
Reviewed. all IDs are nopw passed via query strings

2024-09-05 18:04 UTC, jsvoo commented on collaborators/index.mjs
Oops, new editor on a different device. I missed that setting. Reviewed now.  Thanks

2024-09-09 18:56 UTC, git-voo commented on collaborators/index.mjs
> +                return error.innerHTML = "Unauthorized request. Please log in to view this resource"
Reviewed

2024-09-11 14:02 UTC, git-voo commented on collaborators/index.mjs
> +let error = document.getElementById("error")
I'vce added an issue for this

2024-09-11 14:07 UTC, git-voo commented on collaborators/index.mjs
> +        return roles.join(", ").toLowerCase();
The idea is, if you are an Owner or Leader and have other roles, I want to show the role with the highest permissions. other roles besides these two are just displayed for now

2024-10-25 20:37 UTC, cubap commented
so much good work here, but I think we need to eliminate some of the redundancies. You've already got this instinct. I'm seeing some things that are in `/iiif-tools` and the auth struggles should be handled already. I'm going to go PR something real quick...

2024-10-25 20:43 UTC, cubap commented on _site/api/project.mjs
This directory shouldn't be versioned

2024-11-11 21:52 UTC, cubap requested changes

2024-11-11 21:52 UTC, cubap commented on TPEN/index.mjs
> -import { eventDispatcher } from './events.mjs'
keep this line

2024-11-11 21:52 UTC, cubap commented on TPEN/index.mjs
> -        eventDispatcher.on("tpen-user-loaded", ev=> this.currentUser = ev.detail)
keep this line

2024-11-11 21:52 UTC, cubap commented on TPEN/index.mjs
> -        if (!user.displayName || !user._id) {
I think this `||` is so an unloaded User is never entered in as "#currentUser"

2024-11-11 21:52 UTC, cubap commented on TPEN/index.mjs
> -        const storedToken = localStorage.getItem("userToken")
keep these lines.
They make sure that if the stored token is expired it is removed. This also makes sure that all downstream tokens are valid and current so it doesn't have to be rechecked

2024-11-11 21:52 UTC, cubap commented on TPEN/index.mjs
> +    static logout(redirect = origin + pathname) {
`pathname` is not defined. Shoudl be location.pathname, I believe

2024-11-11 21:52 UTC, cubap commented on TPEN/index.mjs
> -    static attachAuthentication = (element) => {
This arrow function passes through `this`

2024-11-11 21:52 UTC, cubap commented on TPEN/index.mjs
> +        if (!token || checkExpired(token)) {
With the change above, `checkExpired` is redundant.

2024-11-11 21:52 UTC, cubap commented on TPEN/index.mjs
> -        eventDispatcher.dispatch("tpen-authenticated", { detail: token })
Using the eventDispatcher is more reusable and the current line 108 causes an event loop.

2024-11-11 21:52 UTC, cubap commented on TPEN/index.mjs
> +function updateUser(event) {
It is outside of the class and doesn't have a this (except the target of the event, which doesn't work as expected above. The replaced code is better, I think.

2024-11-11 21:52 UTC, cubap commented on TPEN/index.mjs
> -    document?.dispatchEvent(new CustomEvent("tpen-loaded"))
This is still needed for non-module TPEN usage.

2024-11-11 21:52 UTC, cubap commented on User/index.mjs
> +  TPEN = new TPEN()
This should probably be #TPEN, unless we need it exposed outside this.

2024-11-11 21:52 UTC, cubap commented on User/index.mjs
> +    const serviceAPI = `${this.TPEN.servicesURL}/${this.#isTheAuthenticatedUser() ? "my/profile" : `user/:${this._id}`
this winds up calling TPEN.getAuthorization a lot, but it isn't broken, so....
That's why #authentication existed, fwiw.

2024-11-11 21:52 UTC, cubap commented on User/index.mjs
> +      .then((response) => response.json())
Then line this replaces is more concise, just returning response.json() instead of passing it unchanged for a whole new callback.

2024-11-11 21:52 UTC, cubap commented on User/index.mjs
> +        this.display_name ??= TPEN.getAuthorization() ? data.display_name : data.name
this is wrong. The property is called `displayName` and the comment is out of date.

2024-11-11 21:52 UTC, cubap commented on User/index.mjs
> +        if (data.profile) this.profile = data.profile
This check isn't helpful because the output is already controlled by what comes back from the endpoint.

2024-11-11 21:52 UTC, cubap commented on User/index.mjs
> -          eventDispatcher.dispatch("tpen-user-loaded", this)
This line (and the import above) is still needed and how #currentUser gets set in other modules, at the moment.

2024-11-11 21:52 UTC, cubap commented on User/index.mjs
> +    return fetch(`${this.TPEN.servicesURL}/my/projects`, { headers })
This is a good change, I like getting baseURL out of there.

2024-11-11 21:52 UTC, cubap commented on User/index.mjs
> +            Error ${error.status ?? 500}: ${error.statusText ?? "Unknown Server error"}
doubled line

2024-11-11 21:52 UTC, cubap commented on _site/api/project.mjs
> +const baseURL = "http://localhost:3009"
This is taken out of User, it would be nice to use TPEN.servicesURL here too.

2024-11-11 21:52 UTC, cubap commented on _site/api/project.mjs
> +        this.id = projectID
maybe _id is better for consistency.

2024-11-11 21:52 UTC, cubap commented on _site/api/project.mjs
> -        throw new Error("Project ID or configuration is required")
preserving some sort of error may be great so we don't wind up with an empty Project.

2024-11-11 21:52 UTC, cubap commented on _site/api/project.mjs
> +// let projectID = "6602dd2314cd575343f513ba"
remove these comments

2024-11-11 21:52 UTC, cubap commented on _site/api/project.mjs
oops. The whole _site folder should not be versioned.

2024-11-11 21:52 UTC, cubap commented on api/project.mjs
I screwed up and put all the comments for this in the _site/api file above...

2024-11-11 21:52 UTC, cubap commented on index.html
> +    <head>
What happened here? The old page is replicated after the body element is closed?

2024-11-11 21:52 UTC, cubap commented on manage/projectsHighlight.mjs
>  async function fetchProjects() {
seems like a chance to use the Project Class you made.

2024-11-11 21:52 UTC, cubap commented on utilities/checkUserAuthentication.mjs
> +    const authButton = document.querySelector('button[is="auth-button"]')
the new auth-button doesn't have an "is"

2024-11-12 18:31 UTC, git-voo commented on _site/api/project.mjs
> +// let projectID = "6602dd2314cd575343f513ba"
This file is already updated in Project/index.js. we may have to remove this completely

2024-11-12 18:34 UTC, git-voo commented on api/project.mjs
do we even need to keep the api/project.mjs file anymore, we already have it updated in Project/index.mjs

2024-11-19 18:13 UTC, thehabes reviewed
It would be nice if the projects in the project list were clickable to load them up by their id.

Noting it is not possible to delete an item in the project list.  I was informed the API is not ready for that yet, so this makes sense.

In user management I am not able to remove members from a group or change their roles (as an OWNER and/or a LEADER)

In user management I get a conflicting message when I try to add/invite a new member.  The Network says 403 Forbidden.  Pagination says other things.
![image](https://github.com/user-attachments/assets/ffe45e8c-d2f0-4208-aaa4-99212a217749)

/components/user-profile does not load, but the index.html component does.
![image](https://github.com/user-attachments/assets/8cc62bb4-ce51-49b1-abbe-71154368fb61)

I am suspicious of seeing the instances of these two things together...is one of them wrong
- TPEN_USER.authentication
- TPEN_USER.authorization

2024-11-19 18:13 UTC, thehabes commented on components/projects-list/index.mjs
>                  loadedUser.authentication = TPEN.getAuthorization()
authentication vs authorization.  There are instances where this is set like `TPEN_USER.authorization`.  It looks like a difference between TPEN.getAuthorization and checkUserAuthentication and maybe this is right.

2024-11-19 19:50 UTC, cubap commented on manage/index.mjs
> +        loadProjects()
I'm not stressed by the "tabs" as they won't survive the night.

2024-11-19 19:54 UTC, cubap commented on components/projects-list/index.mjs
>                  loadedUser.authentication = TPEN.getAuthorization()
`getAuthorization()` is for consistency from `TPEN_USER`. Strictly speaking, we are getting the idToken, so a refactored name makes sense. That said. This isn't the place for it. Someone can mention this in a new issue, I suppose.

2024-11-25 17:01 UTC, git-voo commented
The UI update for addMember is currently being delayed because of the delayed/no response from the SMTP server since it sends emails. It'd be fixed once the server is back up.

2024-12-03 21:37 UTC, thehabes approved these changes
Noting that the /manage and /collaborators interfaces were tested and appear functional.  Small hotfixes were done in TPEN Services as a consequence of this testing.

Go through the comments to see if anything is still worth addressing before going to `main`.

2024-12-03 21:37 UTC, thehabes commented on User/index.mjs
> +  TPEN = new TPEN()
This comment is still valid.  If it doesn't require too much refactoring consider it.

2024-12-03 21:44 UTC, cubap commented on User/index.mjs
> +  TPEN = new TPEN()
no sweat. I may have done this already on my branch

2024-12-03 22:39 UTC, cubap approved these changes
No unresolved conversations left. There are some things I would like to see different, but my omnipotence is waning.

2024-12-03 22:39 UTC, merged